# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
# Setup guide: https://github.com/lowlighter/metrics/blob/latest/README.md#%EF%B8%8F-using-github-action-on-your-profile-repository-5-min-setup
name: Metrics
on:
  # Schedule updates (every 3rd hour)
  schedule: [{cron: "0 */3 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: nisrulz
          template: classic
          base: activity, community, repositories, metadata
          config_timezone: Europe/Berlin
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_introduction: yes
          plugin_introduction_title: yes
          config_twemoji: yes
          plugin_followup: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          repositories_forks: yes
